Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-04, with the labels that each got.

#291 Add open graph image
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#295 Add the RTP snippet
  templates/layout.html
Labels: Review: Code needed

#296 Shore up get_first_group against missing groups
  helpers.py
Labels: Review: Code +1, Review: QA +1

#298 Remove google analytics snippet
  templates/alternate_index.html
  templates/index.html
Labels: Review: Code +1

#300 Remove angle bracket
  templates/accordion-signup-form.html
Labels: Review: Code +1, Review: QA +1

#301 Replace Google Optimize snippet
  templates/alternate_index.html
  templates/index.html
Labels: Review: Code +1

#303 Remove Google Optimize snippet as causes error
  templates/alternate_index.html
  templates/index.html
Labels: Review: Code +1

#304 Move optimize code to head to fix config warnings
  templates/alternate_index.html
  templates/index.html
  templates/layout.html
Labels: Review: Code +1

#305 Add google optimize snippet to the layout template
  templates/layout.html
Labels: Review: Code +1

#307 Remove duplicated google script
  templates/layout.html
Labels: Review: Code +1

#310 Update cookie-policy dependancy to prevent grid classes from overriding patterns
  package.json
Labels: Review: Code +1, Review: QA +1

#312 remove u-no-margin--top to avoid banners touching posts
  templates/posts.html
Labels: Review: Code +1, Review: QA +1

#316 Remove brighttalk section and feed
  app.py
  templates/alternate_index.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#327 Replace open graph thumbnail
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#325 Update insights logo
  static/sass/styles.scss
  templates/layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1
