Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-11, with the labels that each got.

#424 Add access logs to blog
  entrypoint
Labels: Review: Code needed, Review: QA needed

#422 Upgrade requests to v2.20.0
  requirements.txt
Labels: Review: Code +1

#426 Move from gevent to sync workers
  entrypoint
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#427 Support URL form /{slug}
  app.py
Labels: Review: Code +1, Review: QA +1

#428 Performance speed-ups and better meta data
  helpers.py
  templates/archives.html
  templates/author.html
  templates/cloud-and-server.html
  templates/desktop.html
  templates/group.html
  templates/internet-of-things.html
  templates/layout.html
  templates/post.html
  templates/posts.html
  templates/press-centre.html
  templates/topics.html
  templates/topics/design.html
  templates/topics/juju.html
  templates/topics/maas.html
  templates/topics/snappy.html
  templates/upcoming_posts.html
  templates/whats-coming-up.html
Labels: Review: Code +1, Review: QA +1

#432 Add CircleCI badge
  README.md
Labels: Review: Code +1, Review: QA +1
