Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-05, with the labels that each got.

#332 Add some styling to the orange bar
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#335 Fix wrong number of posts displaying on homepage
  app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#336 Only show featured posts on page one
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#339 Force 16:9 ratio crop for post thumbnails
  static/sass/styles.scss
  templates/alternate_posts.html
  templates/featured-posts.html
  templates/posts.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#341 Show signup form on first page
  templates/posts.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#342 Improve logic to handle thumbnails
  templates/posts.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#345 Change domain name in README
  README.md
Labels: Review: Code needed

#351 313 build new featured content module
  static/sass/_pattern_card.scss
  static/sass/_pattern_strips.scss
  templates/featured-posts.html
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#356 Update featured posts event action
  templates/featured-posts.html
Labels: Review: Code +1, Review: QA +1

#358 Rename to blog
  static/sass/styles.scss
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#330 Bump global nav version
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#362 Singularize category names
  templates/alternate_posts.html
  templates/featured-posts.html
  templates/posts.html
  templates/press-centre.html
  templates/singular-category.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#365 Added robots noindex to search results page
  templates/layout.html
  templates/search.html
Labels: Review: Code +1, Review: QA +1

#367 Fix b version of home page
  app.py
  static/sass/styles.scss
  templates/accordion-signup-form.html
  templates/alternate_index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#369 Update for GDPR
  templates/accordion-signup-form.html
  templates/posts.html
Labels: Review: Code +1, Review: QA +1

#372 Fix the newsletter sign up on the alt homepage
  templates/accordion-signup-form.html
  templates/newsletter-form.html
  templates/posts.html
Labels: Review: Code +1, Review: QA +1
