Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-03, with the labels that each got.

#229 Proxy Insights feed and set correct URL
  app.py
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#230 Include query string in redirects
  redirects.py
Labels: Review: Code +1, Review: QA +1

#245 If displaying a post, add post title to page title
  templates/layout.html
  templates/post.html
Labels: Review: Code +1, Review: QA +1

#247 Slightly simpler title logic
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#249 Fix extra long headings in posts
  static/sass/styles.scss
  templates/post.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#252 Replace press centre photo
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  templates/press-centre.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#250 Add media contacts to press centre
  templates/press-centre.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#263 Temporary redirect for nvidia-gtc-2018
  redirects.yaml
Labels: Priority: High, Review: Code +1, Review: QA +1

#257 Add pagination to homepage
  app.py
  templates/index.html
  templates/pagination.html
Labels: Review: Code +1, Review: QA +1

#262 Add archives link to footer
  templates/layout.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#267 Added route for /webinar/slug route
  app.py
Labels: Review: Code +1, Review: QA +1

#269 Update version to latest global nav
  package.json
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#270 Remove is-bordered class and replace with is-shallow for webinar strip
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#274 Vertically centre social widget on small screens
  static/sass/_pattern_social-share.scss
  templates/post.html
Labels: Review: Code +1, Review: QA +1

#277 Update copy on cloud and server intro
  templates/cloud-and-server.html
Labels: Review: Code +1, Review: QA +1

#278 Add news filter
  templates/posts.html
Labels: Review: Code +1, Review: QA +1

#279 Webteam tooling v3.0.1 and talisker
  .env
  .gitignore
  Dockerfile
  package.json
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#275 Fix search reset button
  static/js/search.js
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#264 Add optional featured images to posts
  api.py
  templates/posts.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#282 Focus search input after clearing
  static/js/search.js
Labels: Review: Code +1, Review: QA +1

#286 Updated author blocks with new API data
  templates/author.html
  templates/post.html
Labels: Review: Code +1, Review: QA +1

#288 Add padding to the top of the sticky newsletter
  templates/newsletter-form.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1
