Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-10, with the labels that each got.

#410 Fix sass-lint command in package.json
  package.json
Labels: Review: Code +1

#411 lossy cloudinary optimisation
  templates/featured-posts.html
  templates/posts.html
  templates/upcoming_posts.html
  templates/whats-coming-up.html
Labels: Review: Code +1, Review: QA +1

#413 Removed google plus from articles and press centre
  templates/post.html
  templates/press-centre.html
Labels: Review: Code +1, Review: QA +1

#414 Use the prometheus_client version that works well with talisker
  requirements.txt
Labels: Priority: Critical, Review: Code +1, Review: QA +1

#416 Added cloudinary to images inside a post content
  helpers.py
  templates/post.html
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#417 Remove double cloudinary urls from images
  helpers.py
Labels: Review: Code needed, Review: QA needed

#418 Fix errors for missing day, month and year in URL
  app.py
Labels: Review: Code +1, Review: QA +1

#419 Gracefully handle missing "from_cache"
  feeds.py
Labels: Review: Code +1, Review: QA +1

#421 Remove prometheus client initialization
  app.py
Labels: Review: Code +1, Review: QA +1
