Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-07, with the labels that each got.

#383 Remove b variant of homepage
  app.py
  redirects.yaml
  static/sass/styles.scss
  templates/accordion-signup-form.html
  templates/alternate_index.html
  templates/alternate_posts.html
Labels: Review: Code +1, Review: QA +1

#388 Updated google tag manager code
  templates/layout.html
  templates/post.html
Labels: Review: Code +1

#389 Add card header style for tutorials and description to first two cards
  static/sass/_pattern_card.scss
  templates/posts.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#390 Re-add GTM to non-post pages
  templates/layout.html
Labels: Priority: High, Review: Code +1
