Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2018-08, with the labels that each got.

#392 Filter out snapcraft tags
  app.py
  helpers.py
Labels: Review: Code +1, Review: QA +1

#402 Use talisker entrypoint as in snapcraft.io
  Dockerfile
  entrypoint
  package.json
  req
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#403 Add net-tools
  Dockerfile
Labels: Review: Code +1

#404 Upgrade Flask, extend timeout
  feeds.py
  requirements.txt
Labels: Review: Code +1, Review: QA +1
