Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2019-05, with the labels that each got.

#530 Remove urlizing the meta description
  templates/post.html
Labels: Review: Code +1, Review: QA +1

#531 Channge "snappy" to "snapcraft" in the nav
  templates/main-nav.html
Labels: Review: Code +1, Review: QA +1

#533 Use xmltodict to strip foreign language content from the RSS feed
  app.py
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#534 Wraps RSS feed manipulation in try block
  app.py
Labels: Review: Code needed, Review: QA needed

#535 Correctly deletes multiple items from feed
  app.py
Labels: Review: Code +1, Review: QA +1

#536 Add service name in logs
  app.py
Labels: Review: Code +1
