Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2019-03, with the labels that each got.

#499 Use correct cookie-policy namespace
  templates/layout.html
Labels: Review: Code +1, Review: QA +1

#498 Add preconnect links to important third-party origins
  templates/layout.html
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#494 Remove funcion remove old entries
  feeds.py
Labels: Review: Code +1, Review: QA +1

#502 Add redirect for 14.04 article
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#505 Update the footer
  static/sass/styles.scss
  templates/layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#508 Strip html from the og:description tag
  templates/layout.html
Labels: Review: Code +1, Review: QA +1
