Repository canonical-web-and-design/blog.ubuntu.com, pull requests merged in 2019-04, with the labels that each got.

#514 Add the robotics newsletter option
  templates/newsletter-form.html
Labels: Review: Code +1, Review: QA +1

#515 Add the robotics topics page
  app.py
  templates/main-nav.html
  templates/topics/robotics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#522 Configure session with talisker
  app.py
  feeds.py
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#524 Exclude chinese posts
  api.py
Labels: Review: Code +1, Review: QA +1

#526 436 sharing links go to the homepage
  templates/post.html
Labels: Review: Code +1, Review: QA +1

#525 Add cta for all robotics blog posts
  static/sass/_pattern_strips.scss
  templates/post.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#527 Deal with missing or bad data
  static/sass/_pattern_card.scss
  templates/posts.html
  templates/singular-category.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1
